apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: groupama-ms-template
  title: MS típusú alkalmazás létrehozása
  description: MS típusú alkalmazás létrehozása
  tags:
    - groupama
    - ms
    - middleware
spec:
  owner: groupama-devops
  system: openshift-idp
  type: service

  parameters:
    - title: MS alkalmazás generáláshoz szükséges adatok
      required:
        - orgName
        - repoName
        - owner
        - system
        - port
      properties:
        orgName:
          title: Alkalmazást fejlesztő csapat neve
          type: string
        repoName:
          title: Repository neve
          type: string
        description:
          title: Leírás
          type: string
          description: Mire szolgál az alkalmazás.
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: Rendszer
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application
    - title: Az alkalmazás metaadatai
      required:
        - groupId
        - artifactId
        - version
        - javaPackageName
      properties:
        groupId:
          title: Maven group Id
          type: string
          default: io.janus
          description: Maven Group ID eg (hu.groupama.hello)
        artifactId:
          title: Maven artifact Id
          type: string
          default: quarkusapp
          description: Maven artifact Id (pl. hello-ms)
        version: 
          title: Verziószám
          type: string
          default: 1.0.0-SNAPSHOT
          description: Maven Artifact Version
        javaPackageName:
          title: Java package név
          type: string
          default: hu.groupama.hello
          description: A java package neve (e.g. hu.groupama.hello) praktikusan megegyezik a maven group id-vel
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on chosen method
          default: ../ci/tekton/
          enum:
            - ../ci/tekton/
          enumNames:
            - Tekton
      dependencies:
        ci:
          oneOf:
            - properties:
                # Show no extra properties when GitHub Actions is selected
                ci:
                  const: ../ci/github-actions/
            - required:
                - imageRepository
                - namespace
                - imageUrl
              properties:
                ci:
                  const: ../ci/tekton/
                imageRepository:
                  title: Select a registry
                  type: string
                  default: quay.io
                  enum:
                    - quay.io
                    - image-registry.openshift-image-registry.svc:5000
                  enumNames:
                    - Quay
                    - Internal OpenShift Registry
                imageUrl:
                  title: Image URL
                  type: string
                  description: The Quay.io or OpenShift Image URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
                namespace:
                  title: Namespace
                  type: string
                  description: The namespace for deploying resources
  steps:
    - id: template
      name: Forráskód generálása
      action: fetch:template
      input:
        url: ./skeleton
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-java
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          version: ${{ parameters.version }}
          javaPackageName: ${{ parameters.javaPackageName}}
          sourceControl: github.com

    - id: ciTemplate
      name: Generating the CI Component
      action: fetch:template
      input:
        url: ${{ parameters.ci }}
        copyWithoutTemplating:
          - .github/workflows/
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-java
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaPackageName: ${{ parameters.javaPackageName}}
          sourceControl: github.com

    - id: publish
      name: Forráskód publikálása
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}
        defaultBranch: main

    - id: register
      name: A komponens regisztrálása a katalógusba
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
